services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${POSTGRES_USER}
      WORDPRESS_DB_PASSWORD: ${POSTGRES_PASSWORD}
      WORDPRESS_DB_NAME: ${POSTGRES_DB}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${POSTGRES_DB}
      MYSQL_USER: ${POSTGRES_USER}
      MYSQL_PASSWORD: ${POSTGRES_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
